# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target '斗鱼S' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 斗鱼S

pod 'Alamofire', '~> 4.5.1'
pod 'Kingfisher', '~> 3.11.0'



end
